swagger: '2.0'
info:
  version: '1.0.0'
  title: 'BankATMapi'
  description: 'provides bank atm  api functions'
paths: 


 /accountinfo/{pin}:
  get:
      operationId: GET_accountinfo-pin
      summary: Returns customer account information
      tags:
        - Accountinfo
      parameters:
        - in: path
          name: pin
          required: true
          type: integer
          minimum: 1
          description: The pin of customers account
      responses:
        200:
          description: A customer account object.
          schema:
            type: object
            properties:
              account_number:
                type: number
                example: 112233445566
              account_name:
                type: string
                example: Vinula Uthsara
              account_balance:
                type: string
                example: Rs.500,000.00
        400:
          description: The specified pin is invalid (e.g. not a number).
        404:
          description: An account with the specified pin was not found.
        default:
          description: Unexpected error        








































# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Vinula/BankATMapi/1.0.0
schemes:
 - https